#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response
apt-get -y update
apt-get -y install nginx
echo 'Hello world!' > /var/www/html/index.nginx-debian.html
line="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=jTX8MSw0Ufw permanent;"
sudo sed -i "26i $line" /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
