#!/usr/bin/env bash
# installing and config load balancer

# Install HAProxy
apt update
apt -y install haproxy

# Configure HAProxy
echo "
frontend load_balancer
  bind :80
  default_backend web_servers
backend web_servers
  balance roundrobin
  server 77035-web-01 35.153.83.70:80
  server 77035-web-02 100.25.196.41:80
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
