#!/usr/bin/env bash
# installing and config load balancer
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*

echo "ENABLED=1" >> /etc/default/haproxy

echo "
frontend load_balancer
    bind :80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 77035-web-01 35.153.83.70:80
    server 77035-web-02 100.25.196.41:80
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
